import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { getRepo, repoSelectors } from "../slice/RepoSlice";
import Link from "next/link";

export default function Home() {
  const dispatch = useDispatch();
  const data = useSelector(repoSelectors.selectAll);
  console.log(data, "data repository");

  useEffect(() => {
    dispatch(getRepo());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Test koding telkom Myteens</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="container mt-5">
        <div className="row d-flex justify-content-center">
          <div className="col-6">
            {data.map((as) => {
              return (
                <div className="card mb-3" style={{ maxwidth: 540 }}>
                  <div className="row g-0">
                    <div className="col-md-4">
                      <img
                        src={as.owner.avatar_url}
                        className="img-fluid rounded-start"
                      />
                    </div>
                    <div className="col-md-8">
                      <div className="card-body">
                        <h6 className="card-title text-uppercase fw-bold">{as.name}</h6>
                        <p className="card-text">{as.description}</p>
                        <h7 className="card-title mt-5">
                          Language :
                          <span class="ms-2 badge bg-secondary">{as.language}</span>
                        </h7>
                        <p className="card-text mt-3">
                          <small className="text-muted">
                            Last updated : {as.updated_at}
                          </small>
                        </p>
                        <Link href={as.html_url}>
                          <button type="button" class="btn btn-outline-primary">
                            Open Repository
                          </button>
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
