import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { getRepo, repoSelectors } from "../slice/RepoSlice";

export default function Home() {
  const dispatch = useDispatch();
  const data = useSelector(repoSelectors.selectAll);
  console.log(data, "data repository");

  useEffect(() => {
    dispatch(getRepo());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Test koding telkom Myteens</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="container mt-5">
        <div className="row d-flex justify-content-center">
          <div className="col-6">
            <div className="card mb-3" style={{maxwidth: 540}}>
              <div className="row g-0">
                <div className="col-md-4">
                  <img  className="img-fluid rounded-start" />
                </div>
                <div className="col-md-8">
                  <div className="card-body">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">
                      This is a wider card with supporting text below as a
                      natural lead-in to additional content. This content is a
                      little bit longer.
                    </p>
                    <p className="card-text">
                      <small className="text-muted">
                        Last updated 3 mins ago
                      </small>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
